config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  # Authentication
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # User registration and password change
  resources :users, only: [:new, :create, :edit, :update]
  
  # Dashboard
  get 'dashboard', to: 'dashboard#index'
  
  # Admin routes
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :users
    resources :stores
  end
  
  # Store owner routes
  namespace :store_owner do
    get 'dashboard', to: 'dashboard#index'
  end
  
  # Normal user routes
  resources :stores, only: [:index, :show] do
    resources :ratings, only: [:create, :update]
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :ratings, dependent: :destroy
  has_many :stores, dependent: :destroy, foreign_key: :owner_id
  
  # Roles enum
  enum role: { normal_user: 0, store_owner: 1, system_admin: 2 }
  
  # Validations
  validates :name, presence: true, length: { minimum: 5, maximum: 60 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :address, presence: true, length: { maximum: 400 }
  validate :password_complexity
  
  private
  
  def password_complexity
    return if password.blank?
    
    unless password.length.between?(8, 16) && 
           password.match(/[A-Z]/) && 
           password.match(/[!@#$%^&*(),.?":{}|<>]/)
      errors.add(:password, "must be 8-16 characters and include at least one uppercase letter and one special character")
    end
  end
end

app/controllers/admin/users_controller.rb
# app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  before_action :set_user, only: [:edit, :update, :destroy]
  
  def index
    @users = User.all
    
    # Apply filters if present
    @users = @users.where("name LIKE ?", "%#{params[:name]}%") if params[:name].present?
    @users = @users.where("email LIKE ?", "%#{params[:email]}%") if params[:email].present?
    @users = @users.where("address LIKE ?", "%#{params[:address]}%") if params[:address].present?
    @users = @users.where(role: params[:role]) if params[:role].present?
    
    # Apply sorting
    sort_column = params[:sort] || "name"
    sort_direction = params[:direction] || "asc"
    @users = @users.order("#{sort_column} #{sort_direction}")
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(admin_user_params)
    
    if @user.save
      redirect_to admin_users_path, notice: "User created successfully"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(admin_user_params)
      redirect_to admin_users_path, notice: "User updated successfully"
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "User deleted successfully"
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def admin_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :address, :role)
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    @user.role = :normal_user
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path, notice: "Account created successfully"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if params[:user][:password].present?
      if @user.update(user_params)
        redirect_to dashboard_path, notice: "Password updated successfully"
      else
        render :edit
      end
    else
      flash.now[:alert] = "Password cannot be blank"
      render :edit
    end
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :address)
  end
  
  def require_login
    unless current_user
      redirect_to login_path, alert: "You must be logged in to access this page"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1>Manage Users</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= user.role %></td>
        <td>
          <%= link_to 'Edit', edit_admin_user_path(user) %> |
          <%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure you want to delete this user?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New User', new_admin_user_path, class: 'button' %>

app/views/admin/users/new.html.erb
<h1>Manage Users</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Role</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= user.role %></td>
        <td>
          <%= link_to 'Edit', edit_admin_user_path(user) %> |
          <%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure you want to delete this user?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New User', new_admin_user_path, class: 'button' %>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>